### ISSUE TITLE
https/ssl support

### ISSUE THREAD

**Issue by jagottsicher** [shesek/bakshish#5]
I love this little daemon, but it does only work with http. 

How can I achieve that does NOT refuse a https connection? Or do I have to set in node.js?

**Comment by shesek** [comment]
I would suggest adding a reverse proxy in front of it, like nginx or apache, to take care of SSL and to forward traffic to the nodejs http server. See [instructions here](https://github.com/toddsby/sailsjs-starter/wiki/Setup-Nginx-reverse-proxy-with-SSL-for-NodeJS).

Alternatively, this could be done from nodejs itself, but this is less recommended for a production environment. I would take a PR for that, but implementing this is not high priority.

**Comment by jagottsicher** [comment]
Nginx as a proxy did the job as described. 

Different from the instructions it is by far easier and more reliable to get a cert from let's encrypt, use the certbot and finally change the settings. If you have a vps or access with ssh it is the easier way. Also, your proxy works with ipv6 eventually.

Thanks! for the advice!
